### ISSUE TITLE
denoising training convergence

### ISSUE THREAD

**Issue by tommymarto** [shuowang666/SQD-MapNet#3]
Dear authors,
before the code was released, my team and I tried to reproduce the results by implementing the method ourselves, but we found it tricky to pick the correct the hyperparameters to ensure that the model had a decent validation score. In other words, it was very hyperparameter-dependent, reaching very low validation when selecting the wrong combination. Did you also happen to find this?

**Comment by shuowang666** [comment]
Hi,
The hyperparameters that need to be set for SQD seem to be many. However, we have found through extensive experiments on different settings that tolerant_noise set to [0.05-0.2], noise_scale_box set to [0.4-0.6], num_dn_queries set to 60, and experiments within these value ranges always result in stable gains and similar experimental results, though optimal performance is not always obtained.
