### ISSUE TITLE
Implementation of the Chamfer distance (directional or bi-directional?).

### ISSUE THREAD

**Issue by Jctrp** [shuowang666/SQD-MapNet#5]
Hi, shuo. Thank you for your wonderful work!
I have some confusion regarding the implementation of chamfer distance in the code. The paper reports the use of bidirectional chamfer distance, but it seems to be a unidirectional implementation in the code?
![图片](https://github.com/user-attachments/assets/6f65fdfc-8656-4eeb-b0d7-f83d93f31c89)

**Comment by shuowang666** [comment]
Hi,
The implementation of the code is bidirectional chamfer distance.

![image](https://github.com/user-attachments/assets/08014204-b011-4a9a-9b65-283fa2bfdea1)

**Comment by Jctrp** [comment]
Hi. Thanks for your response. I've resolved this issue. 😄
